export enum PermissionEnum {
  NotSet = "NotSet",
  StockRead = "StockRead",
  StockAddNew = "StockAddNew",
  StockRemove = "StockRemove",
  SalesRead = "SalesRead",
  SalesSell = "SalesSell",
  SalesReturn = "SalesReturn",
  EmployeeRead = "EmployeeRead",
  OldPermissionNotUsed = "OldPermissionNotUsed",
  AnotherPermission = "AnotherPermission",
  UserRead = "UserRead",
  UserSync = "UserSync",
  UserChange = "UserChange",
  UserRolesChange = "UserRolesChange",
  UserChangeTenant = "UserChangeTenant",
  UserRemove = "UserRemove",
  RoleRead = "RoleRead",
  RoleChange = "RoleChange",
  PermissionRead = "PermissionRead",
  IncludeFilteredPermissions = "IncludeFilteredPermissions",
  TenantList = "TenantList",
  TenantCreate = "TenantCreate",
  TenantUpdate = "TenantUpdate",
  TenantMove = "TenantMove",
  TenantDelete = "TenantDelete",
  AppStatusList = "AppStatusList",
  AppStatusAllDown = "AppStatusAllDown",
  AppStatusTenantDown = "AppStatusTenantDown",
  AppStatusRemove = "AppStatusRemove",
  AccessAll = "AccessAll",
}

